# Generated by Django 3.1.13 on 2021-07-30 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profile.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_id', serialize=False, to='users.user')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('birth_date', models.DateField()),
                ('location', models.CharField(default='', max_length=50)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biography')),
                ('education', models.CharField(default='', max_length=200, verbose_name='Education degree')),
                ('dev_area', models.CharField(choices=[('Full Stack', 'Full Stack'), ('Backend', 'Backend'), ('Frontend', 'Frontend'), ('UX/UI', 'UX/UI')], default='', max_length=50, verbose_name='Main development area')),
                ('main_language', models.CharField(choices=[('Python', 'Python'), ('JavaScript', 'JavaScript'), ('Java', 'Java'), ('C/C++', 'C/C++'), ('C#', 'C#'), ('GO', 'GO'), ('Other language', 'Other language')], default='', max_length=50, verbose_name='Main development language')),
                ('experience', models.TextField(default='')),
                ('website', models.URLField(blank=True, default='', null=True)),
                ('updated_at', models.DateField(auto_now=True, null=True)),
                ('email', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL, verbose_name='User email')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('origin', models.CharField(default='', max_length=60)),
                ('description', models.CharField(default='', max_length=100)),
                ('start_date', models.DateField()),
                ('finish_date', models.DateField(blank=True, default=None, null=True)),
                ('feats_type', models.CharField(choices=[('Certifications', 'Certifications'), ('Languages', 'Languages'), ('Conferences', 'Conferences'), ('Repositories', 'Repositories'), ('Experience', 'Experience'), ('Others', 'Others')], max_length=40)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification', models.ImageField(blank=True, upload_to=profile.models._upload_path)),
                ('user_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='profile.developer')),
            ],
        ),
    ]
