# Generated by Django 3.1.13 on 2021-08-04 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='email',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='user_email', to=settings.AUTH_USER_MODEL, verbose_name='User email'),
        ),
    ]
